<!DOCTYPE HTML>
<meta charset="UTF-8">

<html lang="pt-br">
    <header>
        <title>Teste</title>
        <link rel="stylesheet" href="../../css/header.css">
        <link rel="stylesheet" href="css/login.css">
        <script src="js/login.js"></script>
    </header>

    <body>
        <header class="secondary">
            <p>Login</p>
        </header>

        <main>
            <form method="POST" action="../../database/login.php">
                <label>Login</label>
                <input type="text" placeholder="" name="cpf">
                <label>Senha</label>
                <input type="password" placeholder="********" name="password">
                <input type="submit" value="Entrar">
            </form>
        </main>
    </body>
</html>