<!DOCTYPE HTML>
<meta charset="UTF-8">

<html lang="pt-br">
    <header>
        <title>Teste</title>
        <link rel="stylesheet" href="../../css/header.css">
        <link rel="stylesheet" href="css/alter_book.css">
        <script src="js/alter_book.js"></script>
    </header>

    <body>
        <div id="book-selector-container" class="hidden">
            <h1>Selecionar livro</h1>
            <input type="text" id="search" placeholder="Estou procurando por...">
            <div id="book-list"></div>
            <button id="cancel">Cancelar</button>
        </div>


        <header class="secondary">
            <p>Cadastrar livro</p>
        </header>

        <main>
            <button id="select">Escolher livro</button>
            <form method="POST" action="../../database/alter_book.php">
                <input type="text" placeholder="" name="id" value="-1">
                <label>Título</label>
                <input type="text" placeholder="" name="title">
                <label>Autor</label>
                <input type="text" placeholder="<desconhecido>" name="author">
                <label>Ano de publicação</label>
                <input type="number" placeholder="<desconhecido>" name="year">
                <label>Volume</label>
                <input type="number" placeholder="<desconhecido>" name="volume">
                <label>Edição</label>
                <input type="number" placeholder="<desconhecido>" name="edition">
                <label>Série</label>
                <input type="text" placeholder="<desconhecido / sem série>" name="series">
                <label>Coleção</label>
                <input type="text" placeholder="<desconhecido / sem coleção>" name="collection">
                <label>Número da coleção</label>
                <input type="text" placeholder="<desconhecido / sem coleção>" name="collection_number">
                <label>ISBN</label>
                <input type="text" placeholder="<desconhecido / não possui>" name="isbn">
                <label>Visível?</label>
                <input type="checkbox" placeholder="" name="visibility" checked>
                <input type="submit" value="Continuar">
            </form>
        </main>
    </body>
</html>